---
# Generic Playbook to install and configure apache as an example

#- include_vars: "{{ansible_os_family}}.yml" 
#vars:
#  wp_mysql_db: "{{ domain }}_db"
#  wp_mysql_user: "{{ domain }}_user"
#  wp_mysql_password: "{{ lookup('password', 'credentials/' + client + '/' + tier + '/' + role + '/mysqlpassword length=15') }}"

#- include: domain.yml
