---
# Generic Playbook to install and configure apache as an example

- name: Install PHP and packages - RHEL
  yum:
    name: "{{ packages }}"
    state: installed
#  yum: pkg={{ item }} state=installed
#  with_items: "{{ packages }}" 
  when: ansible_os_family == 'RedHat'

- name: create session path
  file: path={{ session_save_path }} owner={{ apache_user }} group={{ apache_user }} mode=0770 state=directory

- name: copy 00-mpm.conf from template - RHEL
  template: src=00-mpm.conf.j2 dest={{ mpm_conf }}
  when: ansible_os_family == 'RedHat'

