---

- name: Installing php-fpm pkgs - RedHat
  yum:
    name: "{{ php_fpm_pkgs }}"
    state: present
#  yum: name={{ item }} state=present
#  with_items: "{{ php_fpm_pkgs }}"
  when: ansible_os_family == 'RedHat'

- name: Setup www.conf pool
  template: src=www.conf.j2 dest="{{ php_fpm_path }}/www.conf" 
# notify: restart php-fpm

- name: Setup default domain pool
  template: src=example.com.conf.j2 dest="{{ php_fpm_path }}/{{ domain }}.conf"

- name: Setup phpMyAdmin pool
  template: src=phpmyadmin.conf.j2 dest="{{ php_fpm_path }}/phpmyadmin.conf"
  notify: restart php-fpm

#- name: create session path
#  file: path={{ session_save_path }} owner={{ nginx_user }} group={{ nginx_user }} mode=0770 state=directory

- name: Setup log path
  file:
    path: /var/log/php-fpm/php-fpm-pools/{{ domain }}
    state: directory
    owner: '{{ domain_user }}'
    group: '{{ domain_user }}'
    mode: '0711'

- name: Enable php_fpm to start at boot
  service: name={{ php_fpm }} enabled=yes
