---
- hosts: all
  user: root
  become: yes
  vars:
    hello2: "hello.dfas.dfs.ladkfj"

  tasks:
#   - name: clean up hello
     

   - name: hey yo
     debug:
       msg: "{{ hello2 | regex_replace('\\.', '_') }}"
