---
- name: Setup default memached firewall rules - RedHat 6
  command: "/sbin/iptables -I INPUT 2 -i eth2 -p tcp -j ACCEPT"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6' and ansible_eth2 is defined

- name: Save default memached firewall rules - RedHat 6
  command: '/sbin/service iptables save'
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6' and ansible_eth2 is defined

- name: Setup default memached firewall rules - RedHat 7
  command: "/sbin/iptables -I INPUT 2 -i eth2 -p tcp -j ACCEPT"
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7' and ansible_eth2 is defined

- name: Save default memached firewall rules - RedHat 7
  command: '/sbin/service iptables save'
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7' and ansible_eth2 is defined

